# 5. Nombre del workflow
name: generacion

# 6. Configura el workflow para que se dispare con cada push a la rama main
on:
  push:
    branches: [ "Enunciado3" ]

# 7. Define un único job llamado "generar-codigo"
jobs:
  generar-codigo:
    # 8. Configura el job para que se ejecute en ubuntu-latest
    runs-on: ubuntu-latest

    # 9. Define los pasos del job
    steps:
      # 9.1. Paso para descargar el código
      - name: Descargar el código
        uses: actions/checkout@v4

      # 9.2. Paso para configurar Java 17
      - name: Configurar Java 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 9.3. Paso para ejecutar el generador de OpenAPI
      - name: Generar código Python-Flask
        run: java -jar openapi-generator-cli.jar generate -i api.yaml -g python-flask -o ./openapi_server

      # 9.4. Paso para comprimir la salida
      - name: Comprimir el código generado (zip)
        run: zip -r openapi_server.zip openapi_server

      # 9.5. Paso para subir el fichero comprimido como un artefacto
      - name: Subir artefacto (openapi_server.zip)
        uses: actions/upload-artifact@v4
        with:
          # Nombre del artefacto que aparecerá en GitHub
          name: python-flask-server
          # Ruta al archivo que se va a subir
          path: openapi_server.zip
